# Generated by Django 5.1.5 on 2025-02-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clubs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название клуба"
                    ),
                ),
                ("Foundation_date", models.DateField(verbose_name="Дата основания")),
                (
                    "Number_of_players",
                    models.IntegerField(verbose_name="Количество игроков"),
                ),
                (
                    "Conference",
                    models.CharField(
                        choices=[
                            (None, "Выберите конференцию"),
                            ("e", "Восточная"),
                            ("w", "Западная"),
                        ],
                        max_length=1,
                        verbose_name="Конференция",
                    ),
                ),
                (
                    "Registration_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "Total_cost_of_club",
                    models.FloatField(null=True, verbose_name="Общая стоимость клуба"),
                ),
                (
                    "Head_coach",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "t"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coached_clubs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Главный тренер",
                    ),
                ),
                (
                    "Owner",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "o"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_clubs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клуб",
                "verbose_name_plural": "Клубы",
                "db_table": "db_clubs",
            },
        ),
    ]
